<html>
    <head>
        <title>
            about
        </title>
    </head>
    <body>
       <h3>Convenience</h3>
<p> Online stores are usually available 24 hours a day, and many consumers in Western countries have Internet access both at work and at home. Other establishments such as Internet cafes, community centers and schools provide internet access as well. In contrast, visiting a conventional retail store requires travel or commuting and costs such as gas, parking, or bus tickets, and must usually take place during business hours. Delivery was always a problem which affected the convenience of online shopping. However to overcome this many retailers including online retailers in Taiwan brought in a store pick up service. This now meant that customers could purchase goods online and pick them up at a nearby convenience store, making online shopping more advantageous to customers. In the event of a problem with the item (e.g., the product was not what the consumer ordered or the product was not satisfactory), consumers are concerned with the ease of returning an item in exchange for the correct product or a refund. Consumers may need to contact the retailer, visit the post office and pay return shipping, and then wait for a replacement or refund. Some online companies have more generous return policies to compensate for the traditional advantage of physical stores. For example, the online shoe retailer Zappos.com includes labels for free return shipping, and does not charge a restocking fee, even for returns which are not the result of merchant error. (Note: In the United Kingdom, online shops are prohibited from charging a restocking fee if the consumer cancels their order in accordance with the Consumer Protection (Distance Selling) Act 2000).A 2018 survey in the United States found 26% of online shoppers said they never return items, and another 65% said they rarely do so.
</p>
<h3> Information and reviews </h3>
<p> Online stores must describe products for sale with text, photos, and multimedia files, whereas in a physical retail store, the actual product and the manufacturer's packaging will be available for direct inspection (which might involve a test drive, fitting, or other experimentation). Some online stores provide or link to supplemental product information, such as instructions, safety procedures, demonstrations, or manufacturer specifications. Some provide background information, advice, or how-to guides designed to help consumers decide which product to buy. Some stores even allow customers to comment or rate their items. There are also dedicated review sites that host user reviews for different products. Reviews and even some blogs give customers the option of shopping for cheaper purchases from all over the world without having to depend on local retailers. In a conventional retail store, clerks are generally available to answer questions. Some online stores have real-time chat features, but most rely on e-mails or phone calls to handle customer questions. Even if an online store is open 24 hours a day, seven days a week, the customer service team may only be available during regular business hours.
</p>
<h3>Price and selection</h3>
<p>One advantage of shopping online is being able to quickly seek out deals for items or services provided by many different vendors (though some local search engines do exist to help consumers locate products for sale in nearby stores). Search engines, online price comparison services and discovery shopping engines can be used to look up sellers of a particular product or service. Shipping costs (if applicable) reduce the price advantage of online merchandise, though depending on the jurisdiction, a lack of sales tax may compensate for this. Shipping a small number of items, especially from another country, is much more expensive than making the larger shipments bricks-and-mortar retailers order. Some retailers (especially those selling small, high-value items like electronics) offer free shipping on sufficiently large orders. Another major advantage for retailers is the ability to rapidly switch suppliers and vendors without disrupting users' shopping experience.
</p>    
</body>
</html>